"use client";

import { useEffect, useSyncExternalStore } from "react";
import { ShieldAlert } from "lucide-react";

/**
 * 18+ confirmation.
 *
 * Matters more here than it did in the original app: the marketing page used to
 * stand between a visitor and the predictions, and now nothing does — /
 * *is* the board. So this is the first thing an unknown visitor meets.
 *
 * Deliberately not dismissible, and deliberately not tied to an account:
 * the person who needs stopping is the one who never signs in. Confirmation is
 * per-device in localStorage, which is the honest limit of what a client-side
 * gate can claim — it records that the question was asked and answered, not
 * that the answer was true.
 *
 * localStorage is read through useSyncExternalStore rather than in an effect.
 * That gets both halves right at once: the server snapshot says "confirmed" so
 * nothing renders during SSR and there is no hydration mismatch, while the
 * client snapshot reads the real value on the first commit — with no
 * setState-in-effect and no cascading render.
 */

const STORAGE_KEY = "moonodds.age-confirmed";

let cache: boolean | null = null;
const listeners = new Set<() => void>();

function subscribe(fn: () => void) {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

function getSnapshot(): boolean {
  if (cache === null) {
    try {
      cache = localStorage.getItem(STORAGE_KEY) === "true";
    } catch {
      // Private mode: ask every time rather than assume consent.
      cache = false;
    }
  }
  return cache;
}

/** Server renders nothing; the client decides once it can read storage. */
function getServerSnapshot(): boolean {
  return true;
}

function confirmAge() {
  try {
    localStorage.setItem(STORAGE_KEY, "true");
  } catch {
    // Couldn't persist — they'll be asked again next visit. Acceptable.
  }
  cache = true;
  for (const fn of listeners) fn();
}

export function AgeGate() {
  const confirmed = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
  const open = !confirmed;

  // Nothing behind the gate should be reachable — including by scrolling.
  useEffect(() => {
    if (!open) return;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "";
    };
  }, [open]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[100] flex items-end justify-center p-4 sm:items-center"
      role="alertdialog"
      aria-modal="true"
      aria-labelledby="age-gate-title"
      aria-describedby="age-gate-body"
    >
      <div
        className="absolute inset-0"
        style={{ background: "var(--backdrop)", backdropFilter: "blur(4px)" }}
      />

      <div
        className="rise relative w-full max-w-[26rem] overflow-hidden rounded-[2rem] bg-surface p-8 text-center"
        style={{ boxShadow: "var(--shadow-lift)" }}
      >
        <span
          className="mx-auto flex h-14 w-14 items-center justify-center rounded-full"
          style={{ background: "var(--accent-wash)", color: "var(--accent)" }}
        >
          <ShieldAlert className="h-6 w-6" strokeWidth={2} />
        </span>

        <h2 id="age-gate-title" className="display mt-5 text-2xl">
          Are you 18 or older?
        </h2>

        <p
          id="age-gate-body"
          className="mx-auto mt-3 max-w-[22rem] text-[13px] leading-relaxed text-muted"
        >
          MoonOdds is for adults 18 and over. Predictions here are generated by a
          model and are analysis, not guarantees. Gambling can be addictive —
          never stake more than you can afford to lose.
        </p>

        <div className="mt-7 flex flex-col gap-2">
          <button
            type="button"
            onClick={confirmAge}
            className="press h-12 rounded-full bg-accent text-sm font-semibold text-accent-foreground"
          >
            Yes, I&rsquo;m 18 or older
          </button>
          <a
            href="https://www.begambleaware.org"
            className="press flex h-12 items-center justify-center rounded-full border border-border text-sm font-semibold text-muted transition-colors hover:text-foreground"
          >
            No, take me out
          </a>
        </div>
      </div>
    </div>
  );
}
