import Link from "next/link";
import { Logo } from "@/components/brand/logo";
import { Facebook, Twitter, Instagram, Music2 } from "@/components/ui/icons";

/**
 * Site footer.
 *
 * Carries the responsible-gambling notice that used to live at the bottom of
 * the marketing page. With that page gone, this line has to appear on the board
 * itself. It is the one piece of that page nobody should have had to scroll
 * past a sign-up form to read.
 *
 * Layout follows the marketplace convention: a brand column carrying the
 * wordmark and socials, then link columns for what the product is, who makes
 * it, and where to get help. The bottom bar splits copyright from the legal
 * links so the small print reads as a separate register from navigation.
 */

const COLUMNS: { title: string; links: { href: string; label: string }[] }[] = [
  {
    title: "Product",
    links: [
      { href: "/", label: "Today's board" },
      { href: "/slips", label: "My slips" },
      { href: "/profile", label: "Profile" },
    ],
  },
  {
    title: "Company",
    links: [
      { href: "/about", label: "About us" },
      { href: "/contact", label: "Contact" },
    ],
  },
  {
    title: "Help",
    links: [
      { href: "/help", label: "Help centre" },
      { href: "/terms", label: "Terms of use" },
      { href: "/policy", label: "Privacy policy" },
    ],
  },
];

const LEGAL = [
  { href: "/terms", label: "Terms" },
  { href: "/policy", label: "Privacy" },
  { href: "/help", label: "Responsible play" },
];

/**
 * Placeholders, deliberately.
 *
 * They render as inert spans rather than links: a footer icon pointing at a
 * profile that isn't ours is worse than one that goes nowhere. Swap in an
 * anchor when the accounts exist.
 */
const SOCIALS = [
  { label: "Facebook", Icon: Facebook },
  { label: "X", Icon: Twitter },
  { label: "Instagram", Icon: Instagram },
  { label: "TikTok", Icon: Music2 },
];

export function SiteFooter() {
  return (
    <footer className="mt-20 border-t border-border">
      <div className="mx-auto w-full max-w-[110rem] px-5 py-16 sm:px-8 sm:py-20">
        <div className="grid gap-12 md:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr] lg:gap-8">
          <div>
            <Logo />
            <div className="mt-6 flex items-center gap-5">
              {SOCIALS.map(({ label, Icon }) => (
                <span
                  key={label}
                  aria-label={`${label}, coming soon`}
                  title={`${label}, coming soon`}
                  className="text-muted"
                >
                  <Icon className="h-[18px] w-[18px]" />
                </span>
              ))}
            </div>
          </div>

          {COLUMNS.map((col) => (
            <nav key={col.title} aria-label={col.title}>
              <p className="label">{col.title}</p>
              <ul className="mt-6 space-y-4">
                {col.links.map((l) => (
                  <li key={l.href}>
                    <Link
                      href={l.href}
                      className="text-[15px] text-foreground transition-colors hover:text-accent"
                    >
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          ))}
        </div>

        <div className="mt-16 border-t border-separator pt-8">
          <div className="flex flex-wrap items-center justify-between gap-x-8 gap-y-3">
            <p className="text-[13px] text-muted">
              &copy; {new Date().getFullYear()} MoonOdds. All rights reserved.
            </p>
            <nav
              aria-label="Legal"
              className="flex flex-wrap items-center gap-x-8 gap-y-3"
            >
              {LEGAL.map((l) => (
                <Link
                  key={l.label}
                  href={l.href}
                  className="text-[13px] text-muted transition-colors hover:text-foreground"
                >
                  {l.label}
                </Link>
              ))}
            </nav>
          </div>

          <p className="mt-8 text-xs leading-relaxed text-muted">
            18+. MoonOdds is an AI-powered football prediction market. It
            provides analysis, not guarantees, and does not take bets or hold
            funds. Predictions are generated by a model and nothing here is a
            certainty, so never stake more than you can afford to lose. Past
            performance is not necessarily indicative of future results. If
            gambling stops being fun, take a break.{" "}
            <a
              href="https://www.begambleaware.org"
              target="_blank"
              rel="noreferrer noopener"
              className="underline underline-offset-2 hover:text-foreground"
              style={{ color: "var(--link)" }}
            >
              BeGambleAware
            </a>
            .
          </p>
        </div>
      </div>
    </footer>
  );
}
