import Link from "next/link";
import { Logo } from "@/components/brand/logo";
import { Facebook, Twitter, Instagram, Music2 } from "@/components/ui/icons";

/**
 * Site footer.
 *
 * Carries the responsible-gambling notice that used to live at the bottom of
 * the marketing page. With that page gone, this line has to appear on the board
 * itself — it is the one piece of that page nobody should have had to scroll
 * past a sign-up form to read.
 *
 * Link columns follow the marketplace convention: what the product is, how to
 * get help, and the legal footing, in that order.
 */

const COLUMNS: { title: string; links: { href: string; label: string }[] }[] = [
  {
    title: "MoonOdds",
    links: [
      { href: "/", label: "Today's board" },
      { href: "/about", label: "About us" },
      { href: "/slips", label: "My slips" },
    ],
  },
  {
    title: "Support",
    links: [
      { href: "/help", label: "Help centre" },
      { href: "/contact", label: "Contact" },
    ],
  },
  {
    title: "Legal",
    links: [
      { href: "/terms", label: "Terms of use" },
      { href: "/policy", label: "Privacy policy" },
    ],
  },
];

/**
 * Placeholders, deliberately.
 *
 * They point at the site root rather than at guessed handles: a footer icon
 * linking to a profile that isn't ours is worse than one that goes nowhere.
 * Swap the href when the accounts exist.
 */
const SOCIALS = [
  { label: "Facebook", Icon: Facebook },
  { label: "X", Icon: Twitter },
  { label: "Instagram", Icon: Instagram },
  { label: "TikTok", Icon: Music2 },
];

export function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-border">
      <div className="mx-auto w-full max-w-[110rem] px-5 py-12 sm:px-8">
        <div className="grid gap-10 lg:grid-cols-[1fr_2fr]">
          <div>
            <Logo />
            <p className="mt-4 max-w-xs text-[13px] leading-relaxed text-muted">
              AI-read football predictions for the African game and the leagues
              it follows. Analysis, never a guarantee.
            </p>

            <div className="mt-5 flex gap-2">
              {SOCIALS.map(({ label, Icon }) => (
                <span
                  key={label}
                  aria-label={`${label} — coming soon`}
                  title={`${label} — coming soon`}
                  className="flex h-9 w-9 items-center justify-center rounded-full border border-border text-muted"
                >
                  <Icon className="h-4 w-4" />
                </span>
              ))}
            </div>
          </div>

          <nav aria-label="Footer" className="grid grid-cols-2 gap-8 sm:grid-cols-3">
            {COLUMNS.map((col) => (
              <div key={col.title}>
                <p className="label mb-3">{col.title}</p>
                <ul className="space-y-2.5">
                  {col.links.map((l) => (
                    <li key={l.href}>
                      <Link
                        href={l.href}
                        className="text-[13px] text-muted transition-colors hover:text-foreground"
                      >
                        {l.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </nav>
        </div>

        <div className="mt-10 space-y-2 border-t border-separator pt-6">
          <p className="max-w-3xl text-xs leading-relaxed text-muted">
            18+. MoonOdds provides analysis, not guarantees. Predictions are
            generated by a model and nothing here is a certainty — never stake
            more than you can afford to lose. If gambling stops being fun, take a
            break.{" "}
            <a
              href="https://www.begambleaware.org"
              target="_blank"
              rel="noreferrer noopener"
              className="underline underline-offset-2 hover:text-foreground"
              style={{ color: "var(--link)" }}
            >
              BeGambleAware
            </a>
            .
          </p>
          <p className="text-xs text-muted">
            MoonOdds doesn&rsquo;t take bets or hold funds. ©{" "}
            {new Date().getFullYear()} MoonOdds.
          </p>
        </div>
      </div>
    </footer>
  );
}
