import Link from "next/link";

/**
 * Site footer.
 *
 * Carries the responsible-gambling notice that used to live at the bottom of
 * the marketing page. With that page gone, this line has to appear on the board
 * itself — it is the one piece of that page nobody should have had to scroll
 * past a sign-up form to read.
 */
export function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-border">
      <div className="mx-auto w-full max-w-[110rem] space-y-2 px-5 py-10 sm:px-8">
        <p className="max-w-2xl text-xs leading-relaxed text-muted">
          18+. MoonOdds provides analysis, not guarantees. Predictions are
          generated by a model and nothing here is a certainty — never stake more
          than you can afford to lose. If gambling stops being fun, take a break.{" "}
          <a
            href="https://www.begambleaware.org"
            target="_blank"
            rel="noreferrer noopener"
            className="underline underline-offset-2 hover:text-foreground"
            style={{ color: "var(--link)" }}
          >
            BeGambleAware
          </a>
          .
        </p>
        <p className="text-xs text-muted">
          MoonOdds doesn&rsquo;t take bets or hold funds. ©{" "}
          {new Date().getFullYear()} MoonOdds ·{" "}
          <Link href="/profile" className="hover:text-foreground">
            Your account
          </Link>
        </p>
      </div>
    </footer>
  );
}
