import type { Metadata } from "next";
import { createClient } from "@/lib/supabase/server";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { BottomNav } from "@/components/layout/bottom-nav";
import { PageShell, Section } from "@/components/legal/page-shell";

export const metadata: Metadata = {
  title: "Terms of use",
  description: "The terms on which Kicka is provided.",
};

/**
 * Terms of use.
 *
 * Written from scratch to describe this product, rather than adapted from an
 * exchange's or a prediction market's terms. Those documents are drafted for
 * regulated entities that take positions and hold customer funds; Kicka does
 * neither, so borrowing their language would misdescribe the service in ways
 * that matter precisely when a dispute arises.
 */
export default async function TermsPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <>
      <SiteHeader signedIn={!!user} />
      <PageShell
        eyebrow="Legal"
        title="Terms of use"
        intro="Plain terms for a simple product. Read them before you buy a pass."
        updated="15 August 2026"
      >
        <Section title="1. What Kicka provides">
          <p>
            Kicka publishes statistical analysis of football fixtures,
            generated by a model. Each prediction is an opinion about an
            uncertain future event. It is information, not advice, and not a
            recommendation to stake money.
          </p>
          <p>
            Kicka is not a bookmaker, betting exchange, broker or financial
            services provider. We do not accept stakes, hold customer funds, pay
            winnings, or settle wagers. Odds shown alongside a prediction are
            indicative market prices offered for context and are not an offer to
            transact.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 18 years old to use Kicka. We ask for your
            date of birth when you create an account and refuse the account if
            it puts you under 18. That is a declared age, not identity
            verification. You must also comply with the law where you are.
            Betting is restricted or prohibited in some jurisdictions and it is
            your responsibility to know your own position, we do not verify it
            for you.
          </p>
        </Section>

        <Section title="3. Accounts">
          <p>
            You are responsible for keeping your login details secure and for
            everything done through your account. Tell us promptly if you believe
            it has been accessed by someone else.
          </p>
          <p>
            We may suspend an account for abuse, attempted circumvention of
            payment, automated scraping of predictions, or any use that degrades
            the service for others. A suspended account loses access to
            predictions, including on days already paid for.
          </p>
        </Section>

        <Section title="4. Passes and payment">
          <p>
            A day pass grants access to all predictions published on the calendar
            day it is bought, and expires at the end of that day. It renews
            nothing and there is nothing to cancel.
          </p>
          <p>
            If a pass is charged in error, or we fail to publish predictions on a
            day you paid for, contact us and we will refund it. We do not refund
            passes because the predictions were wrong. Uncertainty is the
            substance of what is being sold, and no accuracy level is promised.
          </p>
          <p>
            Payment is handled by our payment processor. We store a reference to
            the transaction, never your card details.
          </p>
        </Section>

        <Section title="5. Slips">
          <p>
            A slip records which predictions you chose to follow so that you can
            track them. Saving a slip places no bet, transfers no money and
            creates no obligation on anyone. Combined odds shown on a slip are
            arithmetic on indicative prices, not a quote.
          </p>
        </Section>

        <Section title="6. No warranty on outcomes">
          <p>
            Predictions are provided as they are. We do not warrant that any
            prediction will prove correct, that any historical accuracy will
            continue, or that the service will be uninterrupted. Published
            performance figures describe the past and do not indicate future
            results.
          </p>
          <p>
            Fixture data, scores and statistics come from third-party providers
            and may be delayed, incomplete or wrong. Where we discover a grading
            error we correct it and record the correction.
          </p>
        </Section>

        <Section title="7. Your use of the content">
          <p>
            Predictions, reasoning and the surrounding material are ours and are
            licensed to you for personal, non-commercial use while you have
            access. You may not republish, resell, redistribute or systematically
            extract them, whether by hand or by automated means.
          </p>
        </Section>

        <Section title="8. Limitation of liability">
          <p>
            To the extent the law allows, Kicka is not liable for losses
            arising from your use of the service, including money staked on any
            event, whether or not a prediction informed that decision. You alone
            decide what to do with the analysis.
          </p>
          <p>
            Nothing here limits liability that cannot lawfully be limited,
            including for fraud.
          </p>
        </Section>

        <Section title="9. Changes">
          <p>
            We may update these terms. Material changes will be signposted in the
            product before they take effect, and the date at the top of this page
            will change. Continuing to use Kicka after that means you accept
            the revision.
          </p>
        </Section>

        <Section title="10. Who you are contracting with">
          <p>
            Kicka is operated by <strong>Keypad Systems</strong>. Your agreement
            is with that entity.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions about these terms go to hello@kicka.app.
          </p>
        </Section>
      </PageShell>
      <SiteFooter />
      <BottomNav />
    </>
  );
}
