/**
 * Generates src/components/ui/icons.tsx.
 *
 * Iconify's default React component fetches icon data from its public API at
 * runtime. That's fine for a prototype and wrong for a product: it puts a
 * third-party CDN on the critical path of every page and leaks which icons a
 * visitor loaded. So instead we bake the handful of icons we actually use into
 * a generated module — 41 path strings rather than the 1,836 in the set.
 *
 * The module exports one component per icon, named exactly as lucide-react
 * named them. That is deliberate: it makes adopting Iconify a one-line import
 * swap per file instead of a rewrite of every call site, which matters when
 * several files bind an icon to a variable (`{ label, Icon }` then `<Icon />`)
 * that no find-and-replace could safely touch.
 *
 * Re-run after adding an icon:  node scripts/generate-icons.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const SET = "lucide";
const OUT = "src/components/ui/icons.tsx";

/** Every icon the app imports today, discovered from the source. */
function usedIcons() {
  const files = execSync(
    `grep -rl 'from "@/components/ui/icons"\\|from "lucide-react"' src/ || true`,
    { encoding: "utf8" },
  )
    .split("\n")
    .filter(Boolean);

  const names = new Set();
  for (const f of files) {
    const src = readFileSync(f, "utf8");
    const re =
      /import\s*\{([^}]*)\}\s*from\s*"(?:lucide-react|@\/components\/ui\/icons)"/gs;
    let m;
    while ((m = re.exec(src))) {
      for (const raw of m[1].split(",")) {
        const n = raw.trim();
        if (n) names.add(n);
      }
    }
  }
  return [...names].sort();
}

/**
 * Icons lucide renamed after the react package we were on.
 *
 * lucide-react still exports the old names as deprecated aliases; the icon set
 * itself only ships the new ones. Mapping them here keeps the call sites
 * unchanged — renaming forty call sites to chase an upstream rename would be
 * churn for no benefit.
 */
const RENAMED = {
  AlertTriangle: "triangle-alert",
  CheckCircle2: "circle-check-big",
  Home: "house",
};

/** AlertTriangle -> alert-triangle, BarChart3 -> bar-chart-3 */
function kebab(pascal) {
  if (RENAMED[pascal]) return RENAMED[pascal];
  return pascal
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

const set = JSON.parse(
  readFileSync(`node_modules/@iconify-json/${SET}/icons.json`, "utf8"),
);

const wanted = usedIcons();
const missing = [];
const entries = [];

for (const name of wanted) {
  const key = kebab(name);
  const icon = set.icons[key];
  if (!icon) {
    missing.push(`${name} (${key})`);
    continue;
  }
  entries.push({ name, key, body: icon.body });
}

if (missing.length) {
  console.error(`Not found in the ${SET} set:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const width = set.width ?? 24;
const height = set.height ?? 24;

const file = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Re-run that script after adding or removing an icon import.
"use client";

import { Icon, addIcon } from "@iconify/react";
import type { ComponentProps } from "react";


/**
 * Iconify icons, bundled offline.
 *
 * Registered up front with addIcon so nothing is fetched at runtime — no CDN
 * on the critical path, no request telling a third party which icons a visitor
 * saw. Data comes from @iconify-json/${SET} at build time.
 *
 * Each export mirrors the lucide-react component it replaced, including the
 * \`strokeWidth\` prop, which is applied as an inherited SVG presentation style
 * on the root so the paths pick it up.
 */

/** Iconify's own props minus the one we supply, plus lucide's strokeWidth. */
type IconProps = Omit<ComponentProps<typeof Icon>, "icon"> & {
  strokeWidth?: number;
};

const W = ${width};
const H = ${height};

${entries
  .map(
    (e) =>
      `addIcon("${SET}:${e.key}", { body: ${JSON.stringify(e.body)}, width: W, height: H });`,
  )
  .join("\n")}

function make(key: string) {
  const C = ({ strokeWidth, style, ...rest }: IconProps) => (
    <Icon
      icon={\`${SET}:\${key}\`}
      style={strokeWidth === undefined ? style : { ...style, strokeWidth }}
      {...rest}
    />
  );
  C.displayName = key;
  return C;
}

${entries.map((e) => `export const ${e.name} = make("${e.key}");`).join("\n")}
`;

writeFileSync(OUT, file);
console.log(`Wrote ${OUT} with ${entries.length} icons from "${SET}".`);
